package main

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/singhpranshu/splitbill/common"
	"github.com/singhpranshu/splitbill/controller"
	_ "github.com/singhpranshu/splitbill/docs"
	db "github.com/singhpranshu/splitbill/repository"
	"github.com/singhpranshu/splitbill/service/handler"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// @title SplitBill API
// @version 1.0
// @description This is the SplitBill API documentation generated by Swag.
// @termsOfService http://swagger.io/terms/
// @contact.name Kajal Rana
// @contact.email kajalrana@example.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /api/v1
func main() {
	config := common.LoadConfig()
	db := db.NewDB(config.DatabaseURL)
	handler := handler.NewHandler(db)

	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), // The url pointing to API definition
	))
	controller.NewUserController(r, handler).RegisterRoutes()
	controller.NewGroupController(r, handler).RegisterRoutes()
	controller.NewSplitController(r, handler).RegisterRoutes()

	http.ListenAndServe(":"+config.Port, r)
}
