// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kajal Rana",
            "email": "kasssjalrana@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/group": {
            "post": {
                "description": "create group details",
                "produces": [
                    "application/json"
                ],
                "summary": "create group data",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/group/member": {
            "post": {
                "description": "create group member details",
                "produces": [
                    "application/json"
                ],
                "summary": "create group member data",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/group/{id}": {
            "get": {
                "description": "Retrieve group details",
                "produces": [
                    "application/json"
                ],
                "summary": "get group data by group id",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/split": {
            "post": {
                "description": "Retrieve split details",
                "produces": [
                    "application/json"
                ],
                "summary": "create split data by group id",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/split/{groupId}": {
            "get": {
                "description": "Retrieve split details",
                "produces": [
                    "application/json"
                ],
                "summary": "get final split data by group id",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/split/{id}": {
            "get": {
                "description": "Retrieve split details",
                "produces": [
                    "application/json"
                ],
                "summary": "get split data by group id",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Retrieve user details",
                "produces": [
                    "application/json"
                ],
                "summary": "create a user by name",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users/{user_name}": {
            "get": {
                "description": "Retrieve user details",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a user by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Name",
                        "name": "user_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "SplitBill API",
	Description:      "This is the SplitBill API documentation generated by Swag.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
